apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-85dh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-85dh
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-85dh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-85dh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-85dh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ltfz-tenant/nodejs-users/simple-nodejs-app-85dh@sha256:d85e813d68a363c82d1ce06454351f17501899d8396a7014aae18d0624c67cb4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
